# application.yml
server:
  port: 8083
spring:
  application:
    name: logging-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        import: optional:nacos:logging-service.yaml
        import-check:
          enabled: false
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shuzimali?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  rocketmq:
    name-server: localhost:9876  # RocketMQ地址
    consumer:
      group: logging-service-group
      max-retry-times: 16       # 消费端最大重试次数
      message-backoff-times: 1000  # 重试间隔(毫秒)
      consume-thread-min: 16      # 消费线程数
      consume-thread-max: 32      # 最大消费线程数
      consume-message-timeout: 30 # 消费超时时间(分钟)

# MyBatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.loggingservice.entity
  configuration:
    map-underscore-to-camel-case: true